# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VISSxk3o0mOugm94GjXp4T7QssXor0fB
"""

import tensorflow as tf
from tensorflow import keras
import numpy as np
import matplotlib.pyplot as plt

from keras.datasets import fashion_mnist

(X_train, y_train), (X_test, y_test) = fashion_mnist.load_data()

X_train.shape

X_train[0]

X_train = X_train / 255
X_test = X_test/ 255

model = keras.models.Sequential([
                                 keras.layers.Flatten(input_shape = (28, 28)),
                                 keras.layers.Dense(256, activation= 'relu'),
                                 keras.layers.Dense(128, activation= 'relu'),
                                 keras.layers.Dense(64, activation= 'relu'),
                                 keras.layers.Dense(10, activation= 'softmax'),

])

model.compile(optimizer ='adam', loss = 'sparse_categorical_crossentropy', metrics =['accuracy'])

model.summary

model.fit(X_train, y_train, epochs = 10)

model.evaluate(X_test, y_test)

print(model.predict(X_train[0].reshape(1, 28, 28)))

print(np.argmax(model.predict(X_train[0].reshape(1, 28, 28))))

print(np.argmax(model.predict(X_train[1].reshape(1, 28, 28))))

